<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- NuGet package information -->
    <PackageId>M365.API.Helper</PackageId>
    <Authors>Laura Kokkarinen</Authors>
    <PackageDescription>Offers extendable helper classes for calling Microsoft Graph and SharePoint Online REST APIs, including authentication.</PackageDescription>
    <PackageProjectUrl>https://github.com/LauraKokkarinen/M365.API.Helper/pkgs/nuget/M365.API.Helper</PackageProjectUrl>
    <RepositoryUrl>https://github.com/LauraKokkarinen/M365.API.Helper</RepositoryUrl>
    <Version>1.0.4</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.2" IncludeAssets="" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.1" />
  </ItemGroup>
  
</Project>
